apiVersion: v1
kind: Service
metadata:
  name: api-svc
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

---     

apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: harfoh/student-api:v1.0.0
          ports:
          - containerPort: 3000
          env:
            - name: POSTGRES_PASSWORD 
              valueFrom:
                configMapKeyRef:
                  name: db-config      
                  key: POSTGRES_PASSWORD 
            - name: DB_HOST
              value: "db-svc.default"


